apiVersion: v1
data:
  relay: |
    exporters:
      logging: {}
      logging/debug:
        loglevel: debug
      logging/info:
        loglevel: info
      otlp:
        endpoint: jaeger-otlp-collector:4318
        sending_queue:
          enabled: true
          queue_size: 600
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 600s
        tls:
          insecure: true
      jaeger:
        endpoint: jaeger-otlp-collector:14250
        tls:
          insecure: true
    extensions:
      health_check: {}
      memory_ballast: {}
    processors:
      batch:
        send_batch_size: 10000
        timeout: 10s
        send_batch_max_size: 11000
      memory_limiter:
        check_interval: 1s
        limit_percentage: 80
        spike_limit_percentage: 75
    receivers:
      jaeger:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14250
          thrift_compact:
            endpoint: 0.0.0.0:6831
          thrift_http:
            endpoint: 0.0.0.0:14268
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
            - targets:
              - 0.0.0.0:8888
      zipkin:
        endpoint: 0.0.0.0:9411
    service:
      extensions:
      - health_check
      pipelines:
        traces:
          exporters:
          - otlp
          processors:
          - batch
          receivers:
          - jaeger
      telemetry:
        logs:
          level: info
        metrics:
          address: 0.0.0.0:8888
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: opentelemetry-collector
    meta.helm.sh/release-namespace: kyma-system
  labels:
    app.kubernetes.io/instance: opentelemetry-collector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/version: 0.60.0
    helm.sh/chart: opentelemetry-collector-0.32.0
  name: opentelemetry-collector
  namespace: kyma-system
